version: "3"
services:
  democracy-mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: democracy-mysql
    environment:
      - MYSQL_DATABASE=democracy
      - MYSQL_ROOT_PASSWORD=12345
      - TZ=Asia/Seoul
  democracy-tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    image: democracy-tomcat
    ports:
      - 18081:8080
    environment:
      - CATALINA_OPTS="-Djava.net.preferIPv4Stack=true -Djava.awt.headless=true"
      - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -Xmx1g -Xms1g -XX:MaxPermSize=128m"
      - Globals.Url=jdbc:mysql://democracy-mysql:3306/democracy?useSSL=false&characterEncoding=UTF-8
      - Globals.Password=12345
      - TZ=Asia/Seoul
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./static:/var/www
    links:
      - democracy-mysql
  democracy-nginx:
    image: nginx:1.15.7
    ports:
      - 18080:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
      - ./webapps/ROOT:/usr/share/nginx/tomcat:ro
    links:
      - democracy-tomcat